name: release-policy

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  release-policy:
    uses: benvon/reusable-workflows/.github/workflows/release-policy.yml@3b5619c1197c291cc1aff9506cdc397717868dcc
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
